# jwt

jwt:
  secret: ENC(K0FEs4AYN7SZ6+ldy4RNuKcwm1oM8ao3pNQ9FKcVMxqgDsw2xYzc1PXjXaJhIdklso7jGkY7diehJ6zlggtpLOTfmwLULykL)
  access-token-expiration-period: ENC(XJ6E2XXCS1BjNx0aJs7TfA==)
  refresh-token-expiration-period: ENC(Pz/0gEw/ieCPy7Fxee8+Sg==)
#  header-name: Authorization

# OAuth2

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: ENC(cGZ2aSg57gtrME04EfID2lBDd/VHSF8AP0f1+MUNJ9k=)
#            client-secret: ENC(cc1Tdktj6b8yo7BBlrVVlGvrQWRh2ou18OG7Ez9c1IZIsLaprF3XMlpi07RcSFNCcgoK8O6vkDE=)
#            redirect-uri: ENC(RTfTf+THRqR8vwtyf5UKB7N/zo27ljU5IU18ND8c8h4kYaoVtD9rsysHCX3Yyy/lBXVWFTv7pUs=)

#request:
#  url:
#    user-server:
#    front-login: