spring:
  # MariaDB
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: org.mysql.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# okhttp request url to store-service
#request:
#  user: ENC(mVQN90HqIlOYcPRrrTyIc5F2we71Z2dC6SXlfUKVtPEkf9+U7d2TwA==)
#  url:  ENC(6tWQjAFg4JB8CYgfEhkEGGS/31xfQZ8UMUm9WC70YgR0Q7NuTz8Q5UYgdKl7oxvDy+8Uk7Txf2to+ZCLClO1Eg==)