spring:
  # MySQL
  datasource:
    url: ENC(3kNnzrLc9rwKYEsSESJ5u7z765z+RzksxElX1lvmXkrjTvmRYk5SMW/5FxX8fRN2UlSJNJ7JBq4SLfBdtFDNcRValL+IRmWGVxdta6PbDck=)
    username: ENC(yRLLXm4+PnvnKSw0EN4Yo+1CI2952xRP)
    password: ENC(E5XNOWaCL+nnrZir1+bzP9xfoGfE/4+C)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#redis

redis:
  host: 3.39.251.120
  port: 16379