spring:
  # MySQL
  datasource:
    url: ENC(iUvSSQ1JxQjI6Z+pAPQqFSyMSsXbmqQca9373SNaBejW2TeHTy919wdkqNg2xGFt)
    username: ENC(bpdA5fYpXTNUWWBQic6JDd4YhWdgDpYT)
    password: ENC(OYDcfZnEyTSXX3kGNVAJgBkv2Oh/cIeE)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#redis

redis:
  host: 3.39.251.120
  port: 16379