server:
  port: 8080

spring:
  application:
    name: key-board

  profiles:
    include:
      - db
      - auth

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

# log level setting
logging:
  level:
    root: info
    com:
      ktds: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
